language: java
jdk:
- openjdk8
deploy:
  provider: releases
  api_key:
    secure: 
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/target/GachaPlus*.jar"
  skip_cleanup: true
  on:
    repo: tunagohan/GachaPlus
    tags: true
notifications:
  email:
    on_success: never
    on_failure: change
