name: GachaPlus
depend: [Jecon]
version: 1.0
api-version: 1.15
description: |
  An existing Gacha plugin with a money element added.
  fork by https://github.com/gorogoro-space/Gacha
  You can set money for each gacha.
  In addition, gacha tickets are issued separately for each gacha instead of being shared.
author: tunagohan
main: com.github.tunagohan.gachaplus.GachaPlus

commands:
  gacha:
    description: Commands to manage your gacha+
    aliases: [gcp]
    usage: |
      Use /help gachaplus [subcommand] for more information
      /<command> list - List all gachaplus
      /<command> modify <gacha_name> - Modify a gachaplus
      /<command> delete <gacha_name> - Delete a gachaplus
      /<command> ticket <player_name> - Issue a ticket
  gachaplus list:
    description: List all gacha
    aliases: [gcp l]
    usage: /<command> list
  gachaplus modify:
    description: Modify a gacha chest
    aliases: [gcp m]
    usage: /<command> modify <gacha_name>
  gachaplus delete:
    description: Delete a gacha
    aliases: [gcp d]
    usage: /<command> delete <gacha_name>
  gachaplus ticket:
    description: Issue a ticket
    aliases: [gcp t]
    usage: /<command> ticket <player_name>
